use crate::commands::schema::{CommandSchema, RiskLevel};

use super::compat_schema;

pub(super) static COMPAT_TRAPS: &[CommandSchema] = &[
    compat_schema(
        "bash",
        "Unix shell (blocked)",
        "Not available in ROY.",
        RiskLevel::Critical,
        "ROY does not provide a bash surface. Use ROY-native commands or `help`.",
    ),
    compat_schema(
        "sh",
        "POSIX shell (blocked)",
        "Not available in ROY.",
        RiskLevel::Critical,
        "ROY does not provide a sh surface. Use ROY-native commands or `help`.",
    ),
    compat_schema(
        "zsh",
        "Z shell (blocked)",
        "Not available in ROY.",
        RiskLevel::Critical,
        "ROY does not provide a zsh surface. Use ROY-native commands or `help`.",
    ),
    compat_schema(
        "fish",
        "fish shell (blocked)",
        "Not available in ROY.",
        RiskLevel::Critical,
        "ROY does not provide a fish surface. Use ROY-native commands or `help`.",
    ),
    compat_schema(
        "csh",
        "C shell (blocked)",
        "Not available in ROY.",
        RiskLevel::Critical,
        "ROY does not provide a csh surface. Use ROY-native commands or `help`.",
    ),
    compat_schema(
        "grep",
        "text search (blocked)",
        "Not available. Use ROY search commands (pending TOOL-02).",
        RiskLevel::Medium,
        "grep is not available here. ROY search commands are pending (TOOL-02).",
    ),
    compat_schema(
        "rg",
        "ripgrep (blocked)",
        "Not available. Use ROY search commands (pending TOOL-02).",
        RiskLevel::Medium,
        "rg is not available here. ROY search commands are pending (TOOL-02).",
    ),
    compat_schema(
        "find",
        "file search (blocked)",
        "Not available. Use ROY workspace inspection (pending TOOL-02).",
        RiskLevel::Medium,
        "find is not available here. ROY workspace inspection is pending (TOOL-02).",
    ),
    compat_schema(
        "cat",
        "file read (blocked)",
        "Not available. Use `read <path>`.",
        RiskLevel::Safe,
        "cat is not available here. Use `read <path>`.",
    ),
    compat_schema(
        "head",
        "file head (blocked)",
        "Not available. Use `read <path>`.",
        RiskLevel::Safe,
        "head is not available here. Use `read <path>`.",
    ),
    compat_schema(
        "tail",
        "file tail (blocked)",
        "Not available. Use `read <path>`.",
        RiskLevel::Safe,
        "tail is not available here. Use `read <path>`.",
    ),
    compat_schema(
        "rm",
        "file remove (blocked)",
        "Not available. Use ROY-native mutation commands (pending TOOL-02).",
        RiskLevel::High,
        "rm is not available here. Use `write` or future ROY-native mutation commands.",
    ),
    compat_schema(
        "mv",
        "file move (blocked)",
        "Not available. Use ROY-native mutation commands (pending TOOL-02).",
        RiskLevel::High,
        "mv is not available here. Use `write` or future ROY-native mutation commands.",
    ),
    compat_schema(
        "cp",
        "file copy (blocked)",
        "Not available. Use ROY-native mutation commands (pending TOOL-02).",
        RiskLevel::Medium,
        "cp is not available here. Use `write` or future ROY-native mutation commands.",
    ),
    compat_schema(
        "curl",
        "HTTP client (blocked)",
        "Not available. Network commands are controlled by ROY policy.",
        RiskLevel::High,
        "curl is not available here. Network commands are controlled by ROY policy.",
    ),
    compat_schema(
        "wget",
        "HTTP download (blocked)",
        "Not available. Network commands are controlled by ROY policy.",
        RiskLevel::High,
        "wget is not available here. Network commands are controlled by ROY policy.",
    ),
    compat_schema(
        "sudo",
        "privilege escalation (blocked)",
        "Not available. ROY controls permissions through its policy engine.",
        RiskLevel::Critical,
        "sudo is not available here. ROY controls permissions through its policy engine.",
    ),
    compat_schema(
        "apt",
        "package manager (blocked)",
        "Not available. ROY manages its own environment.",
        RiskLevel::Critical,
        "apt is not available here. ROY manages its own environment.",
    ),
    compat_schema(
        "apt-get",
        "package manager (blocked)",
        "Not available. ROY manages its own environment.",
        RiskLevel::Critical,
        "apt-get is not available here. ROY manages its own environment.",
    ),
    compat_schema(
        "pip",
        "Python package manager (blocked)",
        "Not available. ROY manages its own environment.",
        RiskLevel::High,
        "pip is not available here. ROY manages its own environment.",
    ),
    compat_schema(
        "npm",
        "Node package manager (blocked)",
        "Not available. ROY manages its own environment.",
        RiskLevel::High,
        "npm is not available here. ROY manages its own environment.",
    ),
    compat_schema(
        "python",
        "Python interpreter (blocked)",
        "Not available. Use ROY-native scripting surfaces (pending).",
        RiskLevel::High,
        "python is not available here. Use ROY-native scripting surfaces (pending).",
    ),
    compat_schema(
        "python3",
        "Python 3 interpreter (blocked)",
        "Not available. Use ROY-native scripting surfaces (pending).",
        RiskLevel::High,
        "python3 is not available here. Use ROY-native scripting surfaces (pending).",
    ),
    compat_schema(
        "node",
        "Node.js interpreter (blocked)",
        "Not available. Use ROY-native scripting surfaces (pending).",
        RiskLevel::High,
        "node is not available here. Use ROY-native scripting surfaces (pending).",
    ),
];
